    <?php if (($narudzba)===0) : ?>
        <div class="no-cart text-center">
            <h2>Niste odabrali još nijedan proizvod.</h2>
            <h5>Naš katalog možete pregledati <a style= " text-decoration: underline " href="<?= App::config('url'); ?>proizvod/">ovdje</a><label class="no-cart-search" for="search"></label></h5>
        </div>
    <?php else : ?>
        <hr>
        <h2 style="color:CornFlowerBlue" sifra="sumTotal">Iznos koji morate platiti: <?= number_format(Narudzba::zbrajanje($_SESSION['autoriziran']->sifra), 2,',','.') ?> kn</h2>
        <br>
        <button  class="button"><a style="color:Yellow" href="<?=App::config('url')?>kosarica/index"> Završi kupovinu</a></button>

    <?php endif; ?>
</div>

