<form class="log2" action="<?=App::config('url')?>login/autoriziraj" method="POST">
  <h4 class="text-center" style="color:CornflowerBlue">Prijava</h4>
  <label style="color:CornflowerBlue">Email
    <input type="email" name="email"  value="<?=$email?>">
  </label>
  <label style="color:CornflowerBlue">Lozinka
    <input type="password" name="lozinka">
  </label>
  <p>
    <input style="width:107px" type="submit" class="button expanded" value="Prijavi se" id="potvrdi-dugme"></input>
  </p>
  <div>
  <h3 style="background-color:yellow" class="button"><a href="<?= App::config('url') ?>registracija/index">Registracija</a></h3>
</div>
</form>

<h5 style="color:CornflowerBlue">email:   khegedus1@gmail.com <br>
    lozinka: a
</h5>
<img src = "<?=App::config('url')?>public/img/era.JPG">