<form class="log-in-form" action="<?=App::config('url')?>login/autoriziraj" method="POST">
  <h4 class="text-center" style="color:blue">Prijava</h4>
  <label style="color:blue">Email
    <input type="email" name="email"  value="<?=$email?>">
  </label>
  <label style="color:blue">Lozinka
    <input type="password" name="lozinka">
  </label>
  <p>
    <input type="submit" class="button expanded" value="Prijavi se" id="potvrdi-dugme"></input>
  </p>
  <span style="color:white"><?=$poruka?></span>
</form>

<h5>email:   khegedus1@gmail.com <br>
    lozinka: a
</h5>