<div class="login-box">
<form action="<?= App::config('url') ?>registracija/noviKupac" method="POST">
  <div class="row collapse expanded">
    <div class="small-12 medium-6 column small-order-2 medium-order-1">
      <div class="login-box-form-section">
        <h3 style="color: CornFlowerBlue" class="login-box-title">Registracija novog kupca</h3>
        <input class="login-box-input" input type="text" name="ime" id="ime" value="<?= $kupac->ime ?>"placeholder="Ime" />
        <input class="login-box-input" input type="text" name="prezime" id="prezime" value="<?= $kupac->prezime ?>"placeholder="Prezime" />
        <input class="login-box-input" input type="text" name="ulica" id="ulica" value="<?= $kupac->ulica ?>"placeholder="ulica" />
        <input class="login-box-input" input type="text" name="kucniBroj" id="kucniBroj" value="<?= $kupac->kucniBroj ?>"placeholder="kucniBroj" />
        <input class="login-box-input" input type="text" name="grad" id="grad" value="<?= $kupac->grad ?>"placeholder="grad" />
        <input class="login-box-input" input type="email" name="email"id="E-mail" value="<?= $kupac->email ?>"placeholder="E-mail" />
        <input type="submit" style="background-color: CornFlowerBlue" class="button expanded" value="Registriraj se" id="potvrdi-dugme"></input>
        <div class="col" >
        </div>
      </div>
      </div>
  </div>
</div>
