<form action="<?=App::config('url')?>proizvod/dodajNovi" method="post" class="forma-unos">

    <fieldset>
        <legend>Dodavanje novog web proizvoda</legend>

    <label for="naziv">Naziv</label>
    <input type="text" name="naziv" id="naziv" value="<?= $proizvod->naziv ?>">

    <label for="cijena">Cijena</label>
    <input type="text" name="cijena" id="cijena" value="<?= $proizvod->cijena ?>">

    <label for="kategorija">Kategorija</label>
    <input type="text" name="kategorija" id="kategorija" value="<?= $proizvod->kategorija ?>">

    <div class="grid-x grid-padding-x">
            <div class="large-4 cell">
                <a  class="alert button expanded" href="<?=App::config('url')?>proizvod/index">Odustani</a>
            </div>
            <div class="large-8 cell">
                <input type="submit" class="success button expanded" value="Dodaj novi">
            </div>
    </div>

    <?=$poruka?>

    </fieldset>

</form>