<form action="<?= App::config('url') ?>kupac/dodajNovi" method="post">

    <fieldset>
    <legend>Dodaj novog kupca</legend>

    <div>
        <div>
            <label>                
             <input type="text" name="ime"  placeholder="Ime" value="<?=$kupac->ime?>"/>
            </label>

            <label>            
                <input type="text" name="prezime"  placeholder="Prezime" value="<?=$kupac->prezime?>"/>
            </label>
        </div>
    </div>
    <div>
        <div>

            <label>
                <input type="text" name="email"  placeholder="email" value="<?=$kupac->email?>"/>
            </label>
        </div>
    </div>

        <div>
            <div>
                <a 
                href="<?=App::config('url')?>kupac/index">Odustani</a>
            </div>
            <div>
                <input type="submit" value="Dodaj novog kupca">
            </div>
        </div>
        <?=$poruka?>
    </fieldset>
</form>