<form action="<?= App::config('url') ?>kupac/promjena" method="post">

    <fieldset>

    <legend class="text-center">Uredi postojeceg kupca</legend>

    <div>
        <div>
            <label>                
             <input type="text" name="ime"  placeholder="Ime" value="<?=$kupac->ime?>"/>
            </label>

            <label>            
                <input type="text" name="prezime" placeholder="Prezime" value="<?=$kupac->prezime?>"/>
            </label>
        </div>
    </div>
    <div>
        <div>
            <label>
                <input type="text" name="email" placeholder="email" value="<?=$kupac->email?>"/>
            </label>
        </div>
    </div>
        <input type="hidden" name="id" value="<?=$kupac->sifra?>">


        <div>
            <div>
                <a
                href="<?=App::config('url')?>kupac/index">Odustani</a>
            </div>
            <div>
                <input type="submit" value="Promjeni">
            </div>
        </div>
        <?=$poruka?>

    </fieldset>
</form>