<div class="title-bar" data-responsive-toggle="example-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle></button>
  <div class="title-bar-title"><?=App::config('naslovApp')?></div>
</div>

<div class="top-bar" id="example-menu" style="background-color: CornflowerBlue">
  <div class="top-bar-left" style="background-color: CornflowerBlue">
    <ul class="dropdown menu" data-dropdown-menu style="background-color: CornflowerBlue">
      <li><a href="<?=App::config('url')?>"><i class="fas fa-home" style="color: yellow"></i></a></li>
      <?php if(App::autoriziran()): ?>
      <?php endif; ?>
      <?php if(App::autoriziran()): ?>
        <li><a href="#" style="color:yellow">Menu</a>
          <ul class="submenu menu vertical" data-submenu style="background-color: CornflowerBlue">
            <li><a href="<?=App::config('url')?>info/index" style="color:yellow">Info</a></li>
            <li><a href="<?=App::config('url')?>proizvod/index" style="color:yellow">Proizvodi</a></li>
            <li><a href="<?=App::config('url')?>uskorouponudi/index" style="color:yellow">Uskoro u ponudi</a></li>
          </ul>
        </li>
      <?php endif; ?>  
    </ul>
  </div>
  <div class="top-bar-right" style="background-color: black">
    <ul class="menu">
      <li style="background-color: yellow">
        <?php if(App::autoriziran()): ?>
          <a class="prijava-dugme" href="<?=App::config('url')?>login/odjava">Odjava <?php echo $_SESSION['autoriziran']->ime ?></a>
        <?php else: ?>
          <a class="prijava-dugme" href="<?=App::config('url')?>login/index">Prijava</a>
        <?php endif; ?>
      </li>
    </ul>
  </div>
</div>