<div class="podnozje">
    <hr <?php
    ?> />


<div id="dmrezeWrap">
    <div class="dmreze">
        <a><img src ="public/img/facebook.jpg"></a>
    </div>

    <div class="dmreze">
        <a><img src ="public/img/instagram.jpg"></a>
    </div>

    <div class="dmreze">
        <a><img src ="public/img/twitter.jpg"></a>
    </div>
    <img id="reklama" src="public/img/footerp.jpg">
</div>
</div>
