<div class="podnozje">
    <hr <?php
    ?> />


<div id="dmrezeWrap">
    <div class="dmreze">
        <a><img src ="<?=App::config('url')?>public/img/facebook.png"></a>
    </div>

    <div class="dmreze">
        <a><img src = "<?=App::config('url')?>public/img/instagram.png"></a>
    </div>

    <div class="dmreze">
        <a><img src ="<?=App::config('url')?>public/img/twitter.jpg"></a>
    </div>
    <div class="dmreze">
        <a><img src ="<?=App::config('url')?>public/img/pinterest.png"></a>
    </div>
    <img id="reklama" src="<?=App::config('url')?>public/img/footerp.png">
</div>
</div>
