<h5>Gaming Webshop posluje od 2022. godine i bavi se prodajom Nintendo,Xbox i Playstation igara. <br> <hr>
Na našoj webstranici imamo bogatu ponudu igara po rekordno niskim cijenama!<br>
Naš cilj je svim kupcima omogućiti najbolje iskustvo kupovine u skladu s Vašim željama, očekivanjima i potrebama.<br>
Ako je vaše iskustvo kupovanja kod nas ugodno, ako ste zadovoljni kvalitetom i cijenom proizvoda te brzinom kojom vam je isti isporučen, naša misija je ostvarena.
<hr>
Nalazimo se na adresi: <b><u>Schlossgasse 58, 5591 Ramingstein,Njemačka</b></u></h5>
<br>
<img id="mario" src = "<?=App::config('url')?>public/img/mario.jpg">

<div class="mapouter"><div class="gmap_canvas"><iframe width="1150" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=Triensberg%20schloss&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe><a href="https://fmovies-online.net">fmovies</a><br><style>.mapouter{position:relative;text-align:right;height:500px;width:600px;}</style><a href="https://www.embedgooglemap.net">iframe google map</a><style>.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:1150px;}</style></div></div>