<div class="main-index">
    <div class="grid-x">
        <div class="cell large-6">
            <h1 style="font-size: 1.5rem;">Narudžbe</h1>
        </div>
    </div>
    <form class="search-product large-6 cell blue-sky" action="<?= App::config('url') ?>kosarica/<?= $type ?>" method="get">
        <div class="ui-widget">
            <input type="text" name="search" id="search" class="search-product" placeholder="Traži po imenu, prezimenu, proizvodu, gradu..." <?= (isset($_GET['search'])) ? 'value="' . $_GET['search'] . '"' : '' ?>>
        </div>
    </form>
    <?php if ($ukupnoNarudzbi == 0) : ?>
        <legend class="total-product-message">Nema niti jedne narudžbe.</legend>
    <?php elseif ($ukupnoNarudzbi == 1) : ?>
        <legend class="total-product-message">Pronađena samo jedna narudžba.</legend>
    <?php elseif ($ukupnoNarudzbi > 1) : ?>
        <legend class="total-product-message">Pronađeno ukupno <?= $ukupnoNarudzbi ?> narudžbi.</legend>

    <?php endif; ?>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Ime</th>
                <th>Prezime</th>
                <th>Grad</th>
                <th>Online</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($narudzba as $kosarica) : ?>
                <tr>
                    <td><?= $kosarica->kosaricaSifra ?></td>
                    <td><?= $kosarica->ime ?></td>
                    <td><?= $kosarica->prezime ?></td>
                    <td><?= $kosarica->grad ?></td>
                    <td><i class="fas fa-info-circle modal" data-id="<?= $kosarica->kosaricaSifra ?>" data-open="modal<?= $kosarica->kosaricaSifra ?>" title="Pogledaj detalje narudžbe."></i></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
